### ISSUE TITLE
Revisions for MVP List

### ISSUE THREAD

**Issue by samsongs1991** [ecbell/OffBeatenPath#2]
1. MVP 3 should be split up into 2 or even 3 separate MVPs. You could do so in the following way.
  - View park profile page and trail profile page
  - Interactive Google Map to search for parks / trails
  - It's not clear from your MVP 3 description if you plan to create a search bar or just search through Google Map. But if you plan to make a search bar, it should be a separate MVP.
  - The reason I say to split these up is because your current MVP 3 will likely take you a lot longer than what you're currently estimating. Keep in mind that CSS styling is included in these time estimates. 

2. To make room for splitting up MVP 3 you could make MVP 4 lighter. 
  - I recommend removing the ability for a user to view other user's pages. That is better left as a low priority bonus feature. Remember that this project is to show off to a recruiter. Your time would be better spent on making your other MVPs amazing.
  - Creating a profile dashboard can suck up A LOT of time. Please keep it light to make sure your main functionalities are high quality. You can fill out more of the dashboard (like settings) as a bonus.

3. If you need to make more room for splitting up MVP 3 you could make MVP 6 a high priority bonus feature.

**Comment by ecbell** [comment]
I revised the MVP, see new version. Perhaps we can talk through it on monday?
