### ISSUE TITLE
Revisions for SCHEMA

### ISSUE THREAD

**Issue by samsongs1991** [ecbell/OffBeatenPath#3]
1. Table names should be snake_cased.
2. users table has a column "first_last" that should be "last_name".
3. trail_conditions_tags has a column "trail_id" that is unnecessary. 
4. trail_conditions_tags has a column "tags". Is this column supposed to contain 1 tag or several tags combined into 1 string? If it is supposed to be 1 tag it should be named "tag".
5. trails table has a tips column which is extra work for you during database seeding as well as coding out your trail profile page that could be saved as a bonus feature.
6. parks table has a "state/region" column which should be "state_region"
7. user_trail_preferences table doesn't seem to align with your MVPs. This should be in the bonus section.
8. trail_conditions_tags table could also be a bonus.

**Comment by ecbell** [comment]
1. Corrected
2. Corrected
3. Corrected to not have trail_id
4. corrected to only have 'tag' => there can be multiple tags per trail but only 1 tag per row.
5. tips is not bonus
6. Corrected
7. - 8. user trail preferences and trail conditions tags are now bonsues. 

I have a total of 5 tables to work on now!
